baoyachi/shadow-rs

example_shadow/Cargo.toml, example_shadow/src/main.rs
link:https://github.com/baoyachi/shadow-rs/issues/12
=> add clap usage

README.md
I think Shadow looks very useful, but I fear it will not get very much attention from the english-speaking Rust community if they cannot easily understand what it provides.
I took the time to rewrite the README in idiomatic English, as I am a native speaker.
=> README Rewrite (by native english speaker)

.github/workflows/check.yml, Cargo.toml, README.md, example_shadow/Cargo.toml, example_shadow/src/main.rs, examples/builtin_method.rs, src/env.rs, src/git.rs, src/lib.rs
* https://github.com/baoyachi/shadow-rs/issues/37
* https://github.com/baoyachi/shadow-rs/issues/38
=> add current branch, semver version const

Cargo.toml, README.md, example_shadow/Cargo.toml, example_shadow/src/main.rs, examples/builtin_method.rs, src/err.rs, src/git.rs, src/lib.rs
=> add feature git2

src/env.rs
Fixes #61, I think. The current tests don't seem to cover even testing the current timestamp system os I didn't see an obvious way to add a test to prove this works.
=> implement standardized variable to enable reproducible builds

.github/workflows/check.yml, example_shadow_hook/src/main.rs, src/env.rs, src/git.rs, src/lib.rs, src/time.rs
=> fix time format without timezone 

Cargo.toml, src/lib.rs
=> docs: Single-sourced cargo feature flags

.github/workflows/check.yml, Cargo.toml, src/lib.rs, src/time.rs
=> fix cross build error 

Cargo.toml, example_shadow/src/main.rs, src/data_time.rs, src/env.rs, src/git.rs, src/lib.rs
=> Make data_time public access 

Cargo.toml, example_shadow/src/main.rs, src/data_time.rs, src/lib.rs
=> Set time crate OffsetDateTime human_format

README.md, src/env.rs, src/lib.rs
=> support CARGO_MANIFEST_DIR const generate

README.md, src/build.rs, src/ci.rs, src/date_time.rs, src/env.rs, src/err.rs, src/gen_const.rs, src/git.rs, src/lib.rs
This adds documentation to all important public items, reworks the main crate documentation, and vastly improves the documentation generated for build constants.
=> Overhaul documentation

Cargo.toml
=> Update tzdb to 0.6.0

.github/workflows/audit.yml
add [security audit](https://github.com/actions-rust-lang/audit) for ci,
=> feature: add security audit

Cargo.toml, example_shadow/src/main.rs, src/build.rs, src/env.rs, src/lib.rs
=> add CARGO_METADATA const

example_shadow/src/main.rs, src/env.rs, src/git.rs, src/lib.rs
=> Default deny gen CARGO_METADATA

Cargo.toml, src/date_time.rs, src/git.rs
=> Fix compilation failures caused by unwrap

src/gen_const.rs, src/lib.rs
=> fix: prevent clippy lints from occuring in the generated file

Cargo.toml
Please merge this, and make a release as soon as possible, as this is a blocker for a package(s) being updated. See https://github.com/NixOS/nixpkgs/pull/341647.
=> Update time crate

src/build.rs, src/git.rs, src/shadow.rs
=> Last tag verbose

.github/workflows/check.yml, Cargo.toml
=> Remove cargo member

src/shadow.rs
=> Fix unit test

src/shadow.rs
=> Gen datetime
