baoyachi/shadow-rs

- Cargo.toml
By default git2 depends on openssl for https transport support, which can be hard to build.
It looks like shadow-rs is read-only so it doesn't really need any of the default features.
> git2: disable default-features

- .github/workflows/check.yml
- Cargo.toml
- README.md
- example_shadow/Cargo.toml
- example_shadow/src/main.rs
- examples/builtin_fn.rs
- src/build_fn.rs
- src/git.rs
- src/lib.rs
> add adapt clap_version()

- src/git.rs
- src/lib.rs
- src/time.rs
This is a follow-up for #61, the value of `TZ` still has an impact on the binary (removing the `env::set_var` call in one of the tests makes the test fail as well):
```
---- time::tests::test_timezone_utc stdout ----
thread 'time::tests::test_timezone_utc' panicked at 'assertion failed: `(left == right)`
left: `"2021-08-04 14:34:03 +02:00"`,
right: `"2021-08-04 12:34:03 +00:00"`', src/time.rs:46:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
With this patch `SOURCE_DATE_EPOCH` makes the embedded timestamp use UTC without build-time localization of the timezone. It also removes build-time localization when embedding the most-recent-git-commit timestamp (this didn't show up in our tests because we've tested with a sourcecode from a tarball).
The code …
> Make embedded timestamps timezone independent

- src/time.rs
Cargo supports some pragmas to force rebuilds if non-Rust sources become "dirtied".
This PR forces cargo to rebuild if the `SOURCE_DATE_EPOCH` env variable changes
since it will change how `now_data_time` and things derived from it are computed.
https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorerun-if-env-changedname
> Rebuild on changes to `SOURCE_DATE_EPOCH`

- README.md
- example_shadow/src/main.rs
- src/build_fn.rs
- src/lib.rs
To maintain compatibility, `clap_version` still exists, its just
deprecated.
Fixes #70
> fix: Replace clap_version with clap_long_version

- Cargo.toml
- src/data_time.rs
tz-rs's `TimeZone::local()` is only supported for Linux hosts, but will
fail e.g. on Windows. Shadow-rs will fallback to use UTC dates, so it
will still be usable on Window.
tzdb's `local_tz()` bundles the Timezone Database, and works on Linux,
Windows, MacOS, FreeBSD, and NetBSD. While having local datetimes on
these host platforms is probably not particularly important, I still
think it's a better user experience.
tzdb itself uses tz-rs to make use of the timezone data.
> Use tzdb to support Windows hosts, too

- Cargo.toml
Shadow-rs uses `std::error::Error`s, which are only implemented by
tz-rs, and tzdb if their features `std` are enabled. Right now this is
not a problem, because even if you are using tzdb without default
features, tzdb still uses tz-rs with default-features. This is because
tz-rs did not yet have the feature gate when tzdb v0.3 was released.
Once tzdb v0.4 is released, the unconditional use of tzdb's std feature
will be fixed, which would break this project. So this PR is proactively
fixing the issue.
> Use tzdb with `std` feature

- Cargo.toml
- src/data_time.rs
This improves the minimum supported rust version a bit, and can be used in cases where having access to the local timezone is less important.
> make `tzdb` an optional dependency

- README.md
While this crate already supported `SOURCE_DATE_EPOCH` it wasn't documented that it does. This change adds the appropriate section to the README.
> Document `SOURCE_DATE_EPOCH`

- Cargo.toml
- src/data_time.rs
- src/env.rs
- src/git.rs
Please see the [changelog](https://docs.rs/tzdb/0.5.0/tzdb/changelog/index.html) for a full list of changes, or compare [`v0.4.5...v0.5.0`](https://github.com/Kijewski/tzdb/compare/v0.4.5...v0.5.0).
> Update to tzdb 0.5.0

- Cargo.toml
- src/date_time.rs
- src/env.rs
- src/git.rs
- src/lib.rs
* add test check
* rename file date_time.rs
> refactor date_time

- src/lib.rs
The generated print_built_in() function triggers uninlined_format_args linter warning.
See https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
With that fix, it generates `"\tprintln!("FOO: {FOO}");\n"` code strings.
Signed-off-by: Samuel Ortiz <sameo@rivosinc.com>
> shadow-rs: Fix linter on generated code

- src/gen_const.rs
Without this change, using `#![deny(missing_docs)]` fails:
```
error: missing documentation for a constant
--> /Users/kartik/GH/project/target/debug/build/project-6de82e90c60d85bc/out/shadow.rs:588:1
|
588 | pub const CLAP_VERSION:&str = shadow_rs::formatcp!(r#"{}
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: the lint level is defined here
--> src/lib.rs:13:9
|
13  | #![deny(missing_docs)]
|         ^^^^^^^^^^^^
```
Another possible change is to remove the deprecated constant itself.
> Allow missing_docs for deprecated CLAP_VERSION constant

- src/git.rs
> Develop a git command to retrieve the corresponding information.

- src/lib.rs
The reason behind this PR:
We have a project "foo" like this:
```text
foo
├── Cargo.toml
├── main.rs
├── my-submodule
│   ├── src
│   │   ├── Cargo.toml
│   │   ├── version.rs
│   │   ├── build.rs
```
The `shadow::new()` is called in `build.rs`, and the `shadow_rs::shadow!(build);` is in `version.rs`.
When I build the project "foo", the git info is that of "my-submodule", instead of "foo", which is not what I actually want(want git info of "foo" of course). This PR expose the "build" function to let projects with submodules decide what the right git repo is. PTAL @baoyachi
> Find the right git info in a project with submodules

- src/git.rs
same reason to the last PR #169 
somehow git2 doesnot find out the branch, so we execute the "git" command in the path where the top most repo resides
> execute "git" command in the right path

- Cargo.toml
- example_shadow_hook/build.rs
- example_shadow_hook/src/main.rs
- src/env.rs
- src/lib.rs
> The update of cargo metadata is controlled through deny const 

- .github/workflows/check.yml
In newest nightly, there's a new clippy lint that triggers false-positively, without ignoring it, current master will be red on re-run
> fix: ignore false-positive clippy lint trigger

- src/shadow.rs
Allow to override build date with `SOURCE_DATE_EPOCH` to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
Fixes #234
> Allow to override generation date

- src/git.rs
I've been having an issue with orphan `index.lock` files in my project, and did some digging to determine that they are being created by `shadow_rs`. I see that `GIT_OPTIONAL_LOCKS=0` is used in most `git` invocations, but is missing from this one in `command_git_status_file`. I believe the reason they are being orphaned in that my editor will kill the build when a file updates, and sometimes this happens while this operation is running.
This PR adds `GIT_OPTIONAL_LOCKS` to the `git` invocation in `command_git_status_file` to avoid creating an `index.lock` that might become an orphan.
Related: https://github.com/baoyachi/shadow-rs/issues/221
> Add GIT_OPTIONAL_LOCKS to git invocation in command_git_status_file
